# Generated by Django 3.0 on 2019-12-22 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldtrip',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Client', verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='soldtrip',
            name='purchased_date',
            field=models.DateField(verbose_name='Дата продажи'),
        ),
        migrations.AlterField(
            model_name='soldtrip',
            name='trip_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Trip', verbose_name='Номер путевки'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_time',
            field=models.DateTimeField(verbose_name='Время отправления'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Номер путевки'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Route', verbose_name='Маршрут'),
        ),
    ]
