# Generated by Django 3.0 on 2019-12-24 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='citizenship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Country', verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='bought',
            field=models.PositiveIntegerField(unique=True, verbose_name='Количество купленных путевок'),
        ),
    ]
